---
driver:
  name: vagrant
  customize:
    natdnsproxy1: 'off'
    natdnshostresolver1: 'off'
  network:
      - ["forwarded_port", {guest: 3306, host: 3456}]
      - ["forwarded_port", {guest: 80, host: 8456}]
  synced_folders: [["../../..", "/vagrant"]]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    attributes:
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
        bind_address: 0.0.0.0
      lamp:
        user: vagrant
        group: vagrant
        mysql:
          user: lamp
          password: lamp
          db_name: lamp
